### ISSUE TITLE
Running 07--diversity_stats on R 4.1.2

### ISSUE THREAD

**Issue by Dahn-YoungDong** [grunwaldlab/metacoder_documentation#11]
Hello,

When I run ggplot2 in the tutorial, it showed error 
`<error/rlang_error>
Corrupt `grouped_df` using old (< 0.8.0) format.
ℹ Strip off old grouping with `ungroup()`.
Backtrace:
  1. ggplot2::ggplot(sample_data, aes(x = Site, y = alpha))
  2. ggplot2:::ggplot.default(sample_data, aes(x = Site, y = alpha))
  4. ggplot2:::fortify.grouped_df(data, ...)
  6. dplyr:::group_indices.data.frame(model)
  7. dplyr::group_rows(.data)
  9. dplyr:::group_data.grouped_df(.data)
 10. dplyr::validate_grouped_df(.data)
Run `rlang::last_trace()` to see the full context.`

Do you know what happened?

**Comment by Dahn-YoungDong** [comment]
It is cloud storage Issue. Solved and you can delete it.

**Comment by zachary-foster** [comment]
Ok, thanks! let me know if you have other problems.
