### ISSUE TITLE
Problem with obj <- filter_obs(obj, "otu_counts", ! has_no_reads) 

### ISSUE THREAD

**Issue by Kaessi** [grunwaldlab/metacoder_documentation#8]
Although all data was loaded correctly, the function
obj <- filter_obs(obj, "otu_counts", ! has_no_reads) results in this error:
Fehler in if (target %in% names(self$data)) { : Argument hat Länge 0

I don't know what kind of example you need, so I just attached a picture of my screen.
If you need anything else to help me solving this questions, please tell me!

Looking forward to your help :)

![Problem-with-filter_obs](https://user-images.githubusercontent.com/44190768/75551232-03fe0600-5a34-11ea-913d-737b7d8b575e.PNG)

**Comment by Kaessi** [comment]
My Session infos:
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxa_0.3.2  dplyr_0.8.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       fansi_0.4.1      utf8_1.1.4       crayon_1.3.4     assertthat_0.2.1 R6_2.4.1        
 [7] jsonlite_1.6.1   magrittr_1.5     pillar_1.4.3     stringi_1.4.4    cli_2.0.1        rlang_0.4.4     
[13] lazyeval_0.2.2   rstudioapi_0.11  vctrs_0.2.2      tools_3.6.2      stringr_1.4.0    glue_1.3.1      
[19] purrr_0.3.3      compiler_3.6.2   pkgconfig_2.0.3  tidyselect_1.0.0 tibble_2.1.3   

And the same problem appears with a function in the exercises:

when I print(obj) everything looks fine,
but the function: 
n_obs(obj) gives the error: 
Fehler in obj$n_obs(data = data, target = target) : 
  unbenutztes Argument (data = data)

Sorry, that the errors are in german, I hope that you can nevertheless help me :)

**Comment by Kaessi** [comment]
@zachary-foster 
I solved the questions by changing the functions to:
1. obj$filter_obs("otu_counts", ! has_no_reads, drop_taxa = TRUE)
2. obj$n_obs("otu_counts")

Without the assignment by $ the function does not run.
Don't know why, but nevertheless my functions now work! Maybe you have got an idea for this issue?

Best regards,
Kathrin

**Comment by zachary-foster** [comment]
Hello Kathrin, 

I cannot reproduce the problem. It seems to work when I run it:

```r
library(dplyr)
library(metacoder)

load("parsed_data.Rdata")

sample_data <- sample_data %>%
  filter(Site %in% c("Mah", "Jam", "Sil"),
         Age == 3) %>%
  group_by(Plant_ID) %>%
  filter(n() == 2)

obj <- filter_taxa(obj, taxon_names != '')
obj <- filter_taxa(obj, taxon_names == 'Bacteria', subtaxa = TRUE)
obj$data$otu_counts <- obj$data$otu_counts[c('taxon_id', 'OTU_ID', sample_data$SampleID)]
has_no_reads <- rowSums(obj$data$otu_counts[, sample_data$SampleID]) == 0
filter_obs(obj, "otu_counts", ! has_no_reads) 
```

```
<Taxmap>
  898 taxa: aad. Bacteria, aaf. Proteobacteria, aag. Actinobacteria ... chi. Anaerobrancaceae, cho. wb1_P06, chs. Alcanivoracaceae
  898 edges: NA->aad, aad->aaf, aad->aag, aad->aah, aad->aai, aad->aaj, aad->aak ... arh->cgz, bdw->chd, azw->chg, bea->chi, anq->cho, apt->chs
  1 data sets:
    otu_counts:
      # A tibble: 21,684 x 294
        taxon_id OTU_ID M1981P563 M1977P1709 M1980P502 M1981P606 M1981P599 M1981P611 M1981P587 M1982P729 M1979P447 M1982P701 M1982P661 M1978P293
        <chr>    <chr>      <dbl>      <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>     <dbl>
      1 ben      2              7          0         2         7         1         7        24         4         3         3      1149         2
      2 beo      3          10251         59     15857       309       134        90     11391        63      6896       497        76        13
      3 ben      4           1447       2496      2421      3331       143      1847      2120      2048      4477      3405      4927      2257
      # … with 21,681 more rows, and 280 more variables: M1980P462 <dbl>, M1555P221 <dbl>, M1980P471 <dbl>, M1979P422 <dbl>, M1982P655 <dbl>,
      #   M1554P182 <dbl>, M1981P623 <dbl>, M1555P239 <dbl>, M1958P1020 <dbl>, M1555P205 <dbl>, …
  0 functions:
```

Can you try to reinstall `taxa` and `metacoder` and try again? Thanks

**Comment by Kaessi** [comment]
Hey Zachary,
I reinstalled taxa and metacoder and tried the functions filter_obs and n_obs again. 
Although I ran your code, I get the same error message. 
Changing the code into: 
obj$filter_obs("otu_counts", ! has_no_reads) 
always works and gives me the right result. Seems that my computer/my RStudio/my R has problems with the functions that contain obs, because n_obs also just works when I change it to
obj$n_obs(). I am a newbie in R, so I have no clue why this function is not working on my PC. 

Best, Kathrin

**Comment by Kaessi** [comment]
Hey Zachary,
I just ran the codes with _obs (n_obs, filter_obs, mutate_obs) with your ex_taxmap object and I got results.
With my obj R does not execude the codes, so something is wrong with my object. But I loaded the supported data via
load("filtered_data.Rdata")
and the I ran all your codes provided on the page
https://grunwaldlab.github.io/analysis_of_microbiome_community_data_in_r/04--manipulating.html

but then I always get errors when running n_obs and so on..
Can I send you any additional information so that you can understand the problem better?

**Comment by Kaessi** [comment]
Sorry to bother you all the time =D 
but I saw that there is a difference in the characteristics of the ex_taxmap and the obj environment (see the images attached)

in ex_taxmap and obj the functions like arrange_obs/filter_obs have different values

Do you see what I mean? And do you have any clue what I did wrong?

![ex_taxmap](https://user-images.githubusercontent.com/44190768/75876558-35047f00-5e16-11ea-992d-a3438beec78d.PNG)
![obj](https://user-images.githubusercontent.com/44190768/75876562-359d1580-5e16-11ea-8464-040589b2a68c.PNG)

**Comment by zachary-foster** [comment]
Hi @Kaessi, 

No problem. Thanks for looking into it. I think I might know what is going on. The objects in the tutorial were produced with an older version of the packages and might need to be updated. I will rebuild the website and get back to you.

**Comment by zachary-foster** [comment]
Hi @Kaessi, 

I updated the website with objects generated from the new packages. Can you try the code again? The objects used in metacoder contain the functions that work with them, which is unusual for most R code.

**Comment by Kaessi** [comment]
Hey @zachary-foster 
now everything works :) Thanks for your help!
I worked with your tutorial on the webpage: https://grunwaldlab.github.io/analysis_of_microbiome_community_data_in_r/03--parsing.html

I am not sure if the data on this webpage is also updated, but with the data from the metacoder page the functions run correctly!
