### ISSUE TITLE
Capitalize taxa in taxon_names

### ISSUE THREAD

**Issue by Kaessi** [grunwaldlab/metacoder_documentation#9]
Hey Zachary,
in my data the taxa are stored uncapitalized (like k_bacteria).
So, after parsing, the taxon names stored in the taxon_names()-function are also uncapitalized.
When I use

str_to_sentence(taxon_names(obj)) 

the names are written with a capital.
Now my question, maybe this is basic, but how can I change the taxon names stored in taxon_names to capital letter?

taxon_names(obj) <- str_to_sentence(taxon_names(obj)) 

gives not the wanted result.

Best regards and thank you for your help :)
Kathrin

**Comment by zachary-foster** [comment]
Hi Kathrin, 

That functionality is part of a big rewrite of the code I am working on. Currently there is no easy way to do it, but this works: 

```r
library(metacoder)
for (i in seq_along(taxon_names(ex_taxmap))) {
  ex_taxmap$taxa[[i]]$name$name <- str_to_sentence(ex_taxmap$taxa[[i]]$name$name)
}
```

Eventually `taxon_names(obj) <- str_to_sentence(taxon_names(obj))` will work.

**Comment by Kaessi** [comment]
Hey Zachary,
perfect that worked :)
Thank you!

**Comment by zachary-foster** [comment]
No problem!
